import {Month} from './month';

export const YEAR:Month[]=[
  {
    index:0,
    monthName:"January",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  },{
    index:1,
    monthName:"February",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:29,
    active:false
  },{
    index:2,
    monthName:"March",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  },{
    index:3,
    monthName:"April",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:30,
    active:false
  },{
    index:4,
    monthName:"May",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  },{
    index:5,
    monthName:"June",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:30,
    active:false
  },{
    index:6,
    monthName:"July",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  },{
    index:7,
    monthName:"August",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  },{
    index:8,
    monthName:"September",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:30,
    active:false
  },{
    index:9,
    monthName:"October",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  },{
    index:10,
    monthName:"November",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:30,
    active:false
  },{
    index:11,
    monthName:"December",
    numberOfWeeks:1,
    startDay:"",
    endDay:"",
    dayCount:31,
    active:false
  }
];
