export const TASKS=[
  {
    taskName:"task1",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1",
        assignmentDate:"",
        completionDate:""
      },
      {
        subtaskName:"subtask2",
        responsible:"person2",
        assignmentDate:"",
        completionDate:""
      },
      {
        subtaskName:"subtask3",
        responsible:"person3",
        assignmentDate:"",
        completionDate:""
      }
    ]
  },
  {
    taskName:"task2",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1",
        assignmentDate:"",
        completionDate:""
      },
      {
        subtaskName:"subtask2",
        responsible:"person2",
        assignmentDate:"",
        completionDate:""
      },
      {
        subtaskName:"subtask3",
        responsible:"person3",
        assignmentDate:"",
        completionDate:""
      },
      {
        subtaskName:"subtask4",
        responsible:"person4",
        assignmentDate:"",
        completionDate:""
      }
    ]
  },{
    taskName:"task3",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1",
        assignmentDate:"",
        completionDate:""
      },
      {
        subtaskName:"subtask2",
        responsible:"person2",
        assignmentDate:"",
        completionDate:""
      }
    ]
  }
];
