export const TASKS=[
  {
    taskName:"task1",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1",
        assignmentDate:"",
        completionDate:"",
        status:"complete",
        priority:1
      },
      {
        subtaskName:"subtask2",
        responsible:"person2",
        assignmentDate:"",
        completionDate:"",
        status:"complete",
        priority:3
      },
      {
        subtaskName:"subtask3",
        responsible:"person3",
        assignmentDate:"",
        completionDate:"",
        status:"issues",
        priority:5
      }
    ]
  },
  {
    taskName:"task2",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1",
        assignmentDate:"",
        completionDate:"",
        status:"inprogress",
        priority:3
      },
      {
        subtaskName:"subtask2",
        responsible:"person2",
        assignmentDate:"",
        completionDate:"",
        status:"issues",
        priority:2
      },
      {
        subtaskName:"subtask3",
        responsible:"person3",
        assignmentDate:"",
        completionDate:"",
        status:"inprogress",
        priority:3
      },
      {
        subtaskName:"subtask4",
        responsible:"person4",
        assignmentDate:"",
        completionDate:"",
        status:"inprogress",
        priority:5
      }
    ]
  },{
    taskName:"task3",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1",
        assignmentDate:"",
        completionDate:"",
        status:"incomplete",
        priority:3
      },
      {
        subtaskName:"subtask2",
        responsible:"person2",
        assignmentDate:"",
        completionDate:"",
        status:"incomplete",
        priority:5
      }
    ]
  }
];
