export const TASKS=[
  {
    taskName:"task1",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1"
      },
      {
        subtaskName:"subtask2",
        responsible:"person2"
      },
      {
        subtaskName:"subtask3",
        responsible:"person3"
      }
    ]
  },
  {
    taskName:"task2",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1"
      },
      {
        subtaskName:"subtask2",
        responsible:"person2"
      },
      {
        subtaskName:"subtask3",
        responsible:"person3"
      },
      {
        subtaskName:"subtask4",
        responsible:"person4"
      }
    ]
  },{
    taskName:"task3",
    subtasks:[
      {
        subtaskName:"subtask1",
        responsible:"person1"
      },
      {
        subtaskName:"subtask2",
        responsible:"person2"
      }
    ]
  }
];
