export const TEAM=[
  {
    name:"Person1",
    isAssigned:true,
    task:"task1",
    subtask:"subtask1",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person2",
    isAssigned:true,
    task:"task1",
    subtask:"subtask2",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person3",
    isAssigned:true,
    task:"task1",
    subtask:"subtask3",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person4",
    isAssigned:true,
    task:"task2",
    subtask:"subtask1",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person5",
    isAssigned:true,
    task:"task2",
    subtask:"subtask2",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person6",
    isAssigned:true,
    task:"task2",
    subtask:"subtask3",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person7",
    isAssigned:true,
    task:"task2",
    subtask:"subtask4",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person8",
    isAssigned:true,
    task:"task3",
    subtask:"subtask1",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person9",
    isAssigned:true,
    task:"task3",
    subtask:"subtask2",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  },{
    name:"Person10",
    isAssigned:true,
    task:"task4",
    subtask:"subtask1",
    assignmentDate:"",
    isComplete:false,
    completionDate:""
  }
];
